# Local configuration. Used for dev. NOT included in releases

# Log to stdout and in debug
logging:
    root:
        level: DEBUG
        handlers:
            - console

# Configure manatory settings with dummy value and point URLs to localhost
bleemeo:
    api_base: http://localhost:8000/
    account_id: 54dfadc4-64a6-4010-a92d-180b1232f282
    registration:
        key: test
    mqtt:
        host: localhost
        ssl: False
        # default is to use /etc/ssl/certs/ca-certificates.crt
        # cafile: /path/to/ca-bundle.crt
        # insecure mean do not check that hostname match. It still check
        # that certificate is signed by a CA
        # ssl_insecure: True

agent:
    # Agent need to write a generated_values.json file. Write it in current directory.
    stored_values_file: generated_values.json
